on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: invite-on-label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: UV-LIS-COATZA
          label: invitacion
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            Bienvenido @{{ sender }} a la comunidad de la licenciatura en ingeniería de software de la UV campus Coatzacoalcos.
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
